insert into [Recept] ([Naziv],[Opis],[TezinaPripremeID],[KategorijaID],[Instrukcija],[Sastojci],[TipID],[VremePripreme],[slika])
select N'Spagete',N'Spagete u sosu',1,2,N'U dublji tiganj, u kojem ćete sve i pripremiti, sipati ulje pa dodati iseckanu slaninu. Proprziti da porumeni i istopi se onaj slaninasti deo.Dok se slanina prži na drugu vatru staviti vodu za testeninu.',N'350 gr špageta, 3 kašike ulja, 350 gr dimljene suve slanine, 1 čen belog luka, so i biber,  prešunov list, 30 gr parmezana, sitno rendanog, 2 jaja',2,N'30 min',N'spagete.jpg' UNION ALL
select N'Pasulj',N'Pasulj sa rebarcima',2,2,N'U sud u kom kuvate pasulj sipati malo ulja i na njega staviti seckani crni i beli luk, dinstati dok ne omekša, pa polako dodavati zelen, šargarepu i papriku, da sve omekša.Sad dodati slaninu, rebra i kobasicu. Zatim dodati i pasulj da se dokuva.',N'pasulj po izboru, suva rebra, slanina barena, dimljena kobasica kranjska, 2 glavice crnog luka, 1 čen belog luka, 1 kom šargarepa.',2,N'2 h',N'pasulj.jpg' UNION ALL
select N'Palačinke',N'Palačinke sa nutelom',1,4,N'Pomešajte jaja sa šećerom i solju u većoj činiji pomoću ručnog miksera. Dodajte pola mleka, ostatak brašna i mleka. Nakon dodavanja pojedinih sastojaka, mešajte mutilicom dok smesa ne postane glatka.Zatim ih ispecite.',N'200 g brašna (tip 400, meko), 2 jajeta, 1 dl ulja, 3 dl mleka i malo mlake vode, kašičica soli i šećera',2,N'30 min',N'palacinke.jpg' UNION ALL
select N'Jaja na oko',N'Pržena jaja sa slaninom',1,1,N'Sipati ulje u tiganj, sacekati da se zagreje. Izlomiti 3 jaja u tiganja. Nakon toga servirati na tanjir.',N'jaja, brasno, zejtin, so, biber, slanina 0,5 kg',2,N'30 min',N'jaja.jpg' UNION ALL
select N'Sendvič',N'Sendvič sa šunkom',1,1,N'U posudi pomešati sitan sir i jaja. Dodati iseckanu šunku, origano i kečap po želji. Sve dobro promešati i fil namazati u tankom sloju između dve kriške. Gornju stranu kriške premazati sa malo putera. Sendviče tostirati par minuta u zagrejanom aparatu za tople sendviče.',N'Tost hleb, 0.5 kg šunke, so, biber, puter, kečap po želji',2,N'15 min',N'sendvic.jpg' UNION ALL
select N'Ćufte',N'Ćufte u sosu',2,2,N'Izmešati sve navedene sastojke za ćufte, zatim oblikovati loptice željene veličine.Sos: Propržiti malo brašno na ulju, dodati pasirani paradajz, izmešati i polako dodavati vodu, zatim dodati začine. Čim proključa, dodavati jednu po jednu lopticu mesa',N'500 g mešanog mlevenog mesa,1 jaje, 1 glavica crnog luka, sitno iseckanog, 3 češnja belog luka, sitno iseckanog, 2 kašike prezli, 2 kašikice suvog biljnog začina, 1 kašika ulja, so, biber',2,N'2 h',N'cufte.jpg' UNION ALL
select N'Pomfrit',N'Hrskavi pomfrit',1,3,N'Iseckati krompir na sitne komade, zatim ga oprati i dodati u zavrleu firtezu ili duboki tiganj.',N'0.5 kg krompira, so, zacini po zelji, biber i ulje',2,N'30 min',N'pomfrit.jpg' UNION ALL
select N'Stek',N'Srednje pečeni stek',2,2,N'Isecite meso na deblje parčiće - oko 3 cm.Biber utrljajte neposredno pred prženje.Podmažite tiganj uljem i ugrejte ga na srednjoj temperaturi.Prvo dobro zapecite šnicle. Kad uhvate koricu s jedne strane, okrenite ih na drugu pa ponovite postupak.',N'500 gr mesa, malo ulja za prženje, 1 kašičica bibera, 1 grančica ruzmarina, 2 čena belog luka, 2 kašike putera, so po ukusu',2,N'1 h',N'stek.jpg' UNION ALL
select N'Bečka šnicla',N'Bečka šnicla sa limunom',3,3,N'Tanko isecene snicle dobro izlupajte na dasci tuckom za meso, sa obe strane. Zatim pazljivo uvaljajte snicle u brasno pazeci da zacini ne spadnu.Zatim uvaljajte ih u umucena jaja, pa dobro utapkajte u prezle. Prziti ih u dubokom, zagrejanom ulju u fritezi ili serpi sa mrezom.',N'6 vecih telecih ili svinjskih snicli, oko 8 kasika brasna, 3 kom. jaja, oko 200gr prezli, 3 cena belog luka, 3 kasicice vegete, malo po ukusu bibera i soli, pola veze persunovog lisca',2,N'1 h',N'becka.jpg' UNION ALL
select N'Ruske kape',N'Čokoladni kolač',3,4,N'Umutiti smesu za fill, zatim za korpu. Ispecite korpu i popunite filom.',N'8 jaja, 13 kašika šećera, 100 g brašna, 5 kašika vode, 1 prašak za pecivo, 3 kašike kakaa',2,N'1 h',N'rkape.jpg';